# baseURL: https://blackchainlife.github.io/
baseURL: http://localhost:1313/
languageCode: zh-Hans
title: Mofaba
theme: PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: false
# mainsections: ["posts", "mofaba"]

minify:
  disableXML: true
  # minifyOutput: truelanguages:
languages:
  en:
    languageName: "Chinese"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: feed
          url: https://github.com/BlackChainLife/personal_blog/feed.xml
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mofaba
  description: "Mofaba description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "Sep 20, 2024"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowShareButtons: false
  ShowAllPagesInArchive: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  # disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  showtoc: true
  tocopen: false

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      👋 Welcome to demo page of Hugo's theme PaperMod!

  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"
    - name: bilibili
      url: "https://bilibili.com"

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Mofaba"
    icon: /apple-touch-icon.png
    iconHeight: 35


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/BlackChainLife/personal_blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #   keys: ["title", "permalink", "summary", "content"]


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false